name: CD - Docker Hub + Kubernetes

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  # ==========================================
  # CI/CD Job 1: Build and Push Docker Images
  # ==========================================
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/cloud-native-devops-platform-backend:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/cloud-native-devops-platform-backend:latest \
            ./backend

      - name: Build frontend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/cloud-native-devops-platform-frontend:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/cloud-native-devops-platform-frontend:latest \
            ./frontend

      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloud-native-devops-platform-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloud-native-devops-platform-backend:latest

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloud-native-devops-platform-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloud-native-devops-platform-frontend:latest


  # ==========================================
  # CD Job 2: Deploy to Local Minikube
  # ==========================================
  deploy:
    name: Deploy to Minikube
    needs: build-and-push
    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Docker
        shell: powershell
        run: |
          docker version

      - name: Verify Kubernetes
        shell: powershell
        run: |
          kubectl version --client
          kubectl get nodes

      - name: Verify Minikube
        shell: powershell
        run: |
          minikube status

      - name: Apply PostgreSQL
        shell: powershell
        run: |
          kubectl apply -f k8s/postgres.yaml

      - name: Apply Backend
        shell: powershell
        run: |
          kubectl apply -f k8s/backend.yaml

      - name: Apply Frontend
        shell: powershell
        run: |
          kubectl apply -f k8s/frontend.yaml

      - name: Restart Backend
        shell: powershell
        run: |
          kubectl rollout restart deployment/backend

      - name: Restart Frontend
        shell: powershell
        run: |
          kubectl rollout restart deployment/frontend

      - name: Wait for Backend
        shell: powershell
        run: |
          kubectl rollout status deployment/backend --timeout=180s

      - name: Wait for Frontend
        shell: powershell
        run: |
          kubectl rollout status deployment/frontend --timeout=180s

      - name: Verify Pods
        shell: powershell
        run: |
          kubectl get pods

      - name: Verify Services
        shell: powershell
        run: |
          kubectl get services